// One config entry per admin-manageable table. The generic API route
// (app/api/admin/[resource]/route.js) and the ResourceManager UI both
// read this to know which table to hit and which columns are editable.
// Adding a new manageable entity is: add a table to schema.sql, add an
// entry here, done — no new API route needed.

import { AMENITY_ICON_OPTIONS, AMENITY_CATEGORY_OPTIONS } from "./amenityIcons";

export const resources = {
  properties: {
    table: "properties",
    label: "Properties",
    orderBy: "created_at DESC",
    listFields: ["id", "title", "listing_type", "property_type", "price", "status", "featured"],
    filters: [
      { key: "_search", label: "Search title / address", type: "search", fields: ["title", "address", "slug"] },
      { key: "listing_type", label: "Listing type", type: "select", options: ["sale", "rent", "commercial"] },
      { key: "property_type", label: "Property type", type: "select", options: ["apartment", "villa", "house", "land", "commercial", "office"] },
      { key: "status", label: "Status", type: "select", options: ["draft", "published", "under_offer", "sold", "rented"] },
      { key: "featured", label: "Featured", type: "select", options: ["1", "0"], optionLabels: { "1": "Yes", "0": "No" } },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true, hint: "Used in the URL, e.g. silverwood-villas" },
      { name: "listing_type", label: "Listing type", type: "select", options: ["sale", "rent", "commercial"], required: true },
      { name: "property_type", label: "Property type", type: "select", options: ["apartment", "villa", "house", "land", "commercial", "office"], required: true },
      { name: "category_id", label: "Category", type: "number" },
      { name: "subcategory_id", label: "Subcategory", type: "number" },
      { name: "price", label: "Price", type: "number", required: true },
      { name: "price_period", label: "Price period", type: "select", options: ["one_time", "monthly", "yearly"] },
      { name: "bedrooms", label: "Bedrooms", type: "number" },
      { name: "bathrooms", label: "Bathrooms", type: "number" },
      { name: "area_sqm", label: "Plot / land area (m²)", type: "number" },
      { name: "carpet_area_sqm", label: "Carpet area (m²)", type: "number" },
      { name: "built_up_area_sqm", label: "Built-up area (m²)", type: "number" },
      { name: "address", label: "Address", type: "text" },
      { name: "location_id", label: "City", type: "number" },
      { name: "latitude", label: "Latitude", type: "number" },
      { name: "longitude", label: "Longitude", type: "number" },
      { name: "cover_image_url", label: "Cover image URL", type: "text" },
      { name: "video_url", label: "Video URL", type: "text" },
      { name: "agent_id", label: "Agent", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["draft", "published", "under_offer", "sold", "rented"] },
      { name: "featured", label: "Featured on homepage", type: "checkbox" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  categories: {
    table: "categories",
    label: "Categories",
    orderBy: "sort_order ASC",
    listFields: ["id", "name", "slug", "sort_order"],
    filters: [
      { key: "_search", label: "Search name / slug", type: "search", fields: ["name", "slug"] },
    ],
    fields: [
      { name: "name", label: "Category name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  subcategories: {
    table: "subcategories",
    label: "Subcategories",
    orderBy: "sort_order ASC",
    listFields: ["id", "name", "category_id", "slug", "sort_order"],
    filters: [
      { key: "_search", label: "Search name / slug", type: "search", fields: ["name", "slug"] },
    ],
    fields: [
      { name: "category_id", label: "Category ID", type: "number", required: true, hint: "See the Categories page for IDs." },
      { name: "name", label: "Subcategory name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  amenities: {
    table: "amenities",
    label: "Amenities",
    orderBy: "sort_order ASC",
    listFields: ["id", "name", "category", "icon_key", "sort_order"],
    filters: [
      { key: "_search", label: "Search name", type: "search", fields: ["name"] },
      { key: "category", label: "Category", type: "select", options: AMENITY_CATEGORY_OPTIONS },
    ],
    fields: [
      { name: "name", label: "Amenity name", type: "text", required: true, hint: "Shown as the checkbox label when creating a property." },
      { name: "category", label: "Category", type: "select", options: AMENITY_CATEGORY_OPTIONS, required: true, hint: "Which section this shows under on the property page." },
      { name: "icon_key", label: "Icon", type: "select", options: AMENITY_ICON_OPTIONS, required: true },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  carpet_area_presets: {
    table: "carpet_area_presets",
    label: "Carpet Area Presets",
    orderBy: "sort_order ASC",
    listFields: ["id", "label", "subcategory_id", "carpet_area_sqm", "built_up_area_sqm", "bedrooms"],
    filters: [
      { key: "_search", label: "Search label", type: "search", fields: ["label"] },
    ],
    fields: [
      { name: "subcategory_id", label: "Subcategory ID", type: "number", required: true, hint: "See the Subcategories page for IDs — e.g. Apartment, Villa, House." },
      { name: "label", label: "Label", type: "text", required: true, hint: "Shown in the property form, e.g. \"2 BHK\"." },
      { name: "carpet_area_sqm", label: "Carpet area (m²)", type: "number", required: true },
      { name: "built_up_area_sqm", label: "Built-up area (m²)", type: "number" },
      { name: "bedrooms", label: "Bedrooms", type: "number" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  projects: {
    table: "projects",
    label: "New Projects",
    orderBy: "created_at DESC",
    listFields: ["id", "name", "status", "starting_price", "total_units", "handover_date"],
    filters: [
      { key: "_search", label: "Search name / slug", type: "search", fields: ["name", "slug"] },
      { key: "status", label: "Status", type: "select", options: ["presale", "under_construction", "selling", "completed"] },
    ],
    fields: [
      { name: "name", label: "Project name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "status", label: "Status", type: "select", options: ["presale", "under_construction", "selling", "completed"] },
      { name: "handover_date", label: "Handover date", type: "date" },
      { name: "starting_price", label: "Starting price", type: "number" },
      { name: "total_units", label: "Total units", type: "number" },
      { name: "cover_image_url", label: "Cover image URL", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  agents: {
    table: "agents",
    label: "Agents",
    orderBy: "id DESC",
    listFields: ["id", "agency_name", "years_experience", "rating", "review_count"],
    filters: [
      { key: "_search", label: "Search agency name", type: "search", fields: ["agency_name", "license_number"] },
    ],
    fields: [
      { name: "user_id", label: "User ID (linked account)", type: "number", required: true, hint: "Create the person under Users first, then link their ID here" },
      { name: "agency_name", label: "Agency name", type: "text" },
      { name: "license_number", label: "License number", type: "text" },
      { name: "years_experience", label: "Years experience", type: "number" },
      { name: "whatsapp", label: "WhatsApp number", type: "text" },
      { name: "rating", label: "Rating (0–5)", type: "number" },
      { name: "review_count", label: "Review count", type: "number" },
      { name: "bio", label: "Bio", type: "textarea" },
    ],
  },
  developers: {
    table: "developers",
    label: "Developers",
    orderBy: "id DESC",
    listFields: ["id", "company_name", "founded_year", "website"],
    filters: [
      { key: "_search", label: "Search company name / website", type: "search", fields: ["company_name", "website"] },
    ],
    fields: [
      { name: "user_id", label: "User ID (linked account)", type: "number", required: true },
      { name: "company_name", label: "Company name", type: "text", required: true },
      { name: "founded_year", label: "Founded year", type: "number" },
      { name: "website", label: "Website", type: "text" },
      { name: "logo_url", label: "Logo URL", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  blog_posts: {
    table: "blog_posts",
    label: "Blog / News",
    orderBy: "id DESC",
    listFields: ["id", "title", "category", "status", "published_at"],
    filters: [
      { key: "_search", label: "Search title / slug", type: "search", fields: ["title", "slug", "category"] },
      { key: "status", label: "Status", type: "select", options: ["draft", "published"] },
      { key: "category", label: "Category", type: "search", fields: ["category"] },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "cover_image_url", label: "Cover image URL", type: "text" },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "content", label: "Content", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["draft", "published"] },
      { name: "published_at", label: "Published at", type: "date" },
    ],
  },
  faqs: {
    table: "faqs",
    label: "FAQs",
    orderBy: "sort_order ASC",
    listFields: ["id", "question", "category", "sort_order"],
    filters: [
      { key: "_search", label: "Search question / answer", type: "search", fields: ["question", "answer", "category"] },
    ],
    fields: [
      { name: "question", label: "Question", type: "text", required: true },
      { name: "answer", label: "Answer", type: "textarea", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  locations: {
    table: "locations",
    label: "Locations",
    orderBy: "id ASC",
    listFields: ["id", "city", "country", "slug"],
    filters: [
      { key: "_search", label: "Search city / region", type: "search", fields: ["city", "region", "slug"] },
      { key: "country", label: "Country", type: "search", fields: ["country"] },
    ],
    fields: [
      { name: "city", label: "City", type: "text", required: true },
      { name: "region", label: "Region", type: "text" },
      { name: "country", label: "Country", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "cover_image_url", label: "Cover image URL", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  inquiries: {
    table: "inquiries",
    label: "Enquiries",
    orderBy: "created_at DESC",
    listFields: ["id", "name", "email", "phone", "status", "created_at"],
    filters: [
      { key: "_search", label: "Search name / email / phone", type: "search", fields: ["name", "email", "phone"] },
      { key: "status", label: "Status", type: "select", options: ["new", "contacted", "closed"] },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "email", label: "Email", type: "text", required: true },
      { name: "phone", label: "Phone", type: "text" },
      { name: "message", label: "Message", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["new", "contacted", "closed"] },
    ],
  },
  visit_requests: {
    table: "visit_requests",
    label: "Schedule Requests",
    orderBy: "created_at DESC",
    listFields: ["id", "name", "phone", "preferred_date", "preferred_time", "status", "created_at"],
    filters: [
      { key: "_search", label: "Search name / email / phone", type: "search", fields: ["name", "email", "phone"] },
      { key: "status", label: "Status", type: "select", options: ["new", "contacted", "scheduled", "closed"] },
      { key: "preferred_date", label: "Date", type: "search", fields: ["preferred_date"] },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "email", label: "Email", type: "text", required: true },
      { name: "phone", label: "Phone", type: "text" },
      { name: "property_id", label: "Property ID", type: "number" },
      { name: "preferred_date", label: "Preferred date", type: "text" },
      { name: "preferred_time", label: "Preferred time", type: "text" },
      { name: "message", label: "Message", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["new", "contacted", "scheduled", "closed"] },
    ],
  },
};
