// Canonical amenity -> icon mapping, shared by the admin Amenities resource
// (icon picker), the property form (checkbox icons), and the public property
// page (feature icons). Keyed by a stable snake_case icon key so the DB only
// ever stores that key, never a component reference.

import {
  Sun, SunMedium, Car, Waves, PawPrint, Briefcase, ConciergeBell, Trees, Dumbbell, Wifi,
  Snowflake, Flame, FlameKindling, ShieldCheck, Shield, ShieldAlert, Warehouse, Zap, Users, UserCheck, Tv,
  WashingMachine, Wind, Lock, KeyRound, Camera, Sofa, UtensilsCrossed, Building2, Building,
  Landmark, Trophy, Baby, Sparkles, Accessibility, BatteryCharging, Droplet, Droplets,
  PhoneCall, Flower2, PanelTop, Footprints, PartyPopper, Video, Cpu, AlertTriangle,
  FireExtinguisher, Fingerprint, ClipboardList, ClipboardCheck, CloudRain, Recycle, Trash2,
  ChefHat, Fan, Shirt, DoorClosed, DoorOpen, Layers, Gem, TreePine, Bath, BookOpen, Wrench, Route,
  CornerDownRight, GraduationCap, HeartPulse, ShoppingBag, ShoppingCart, TrainFront, Plane,
  Mountain, Eye, Clapperboard, Martini, SprayCan,
  // ---- added for Smart / Energy / Advanced Security / Building /
  // Premium Lifestyle / Hotel Services / Advanced Parking / View categories ----
  Lightbulb, Blinds, Bell, Radar, Thermometer, Gauge, Smartphone, Leaf, Award,
  ScanFace, Siren, Hammer, VolumeX, Bike, Dog, Gamepad2, Music, HandHeart,
  GlassWater, Truck, HandPlatter, Package, Sunrise, Sunset,
} from "lucide-react";

// Property-page display groups. Order here is the display order on the
// property detail page and the section order in the admin amenity picker.
export const AMENITY_CATEGORIES = [
  { key: "parking_convenience", label: "Parking & Convenience", emoji: "🚗" },
  { key: "outdoor_lifestyle", label: "Outdoor & Lifestyle", emoji: "🌳" },
  { key: "security_smart", label: "Security & Smart Features", emoji: "🔐" },
  { key: "utilities_infrastructure", label: "Utilities & Infrastructure", emoji: "⚡" },
  { key: "interior_features", label: "Interior Features", emoji: "🛋️" },
  { key: "location_nearby", label: "Location & Nearby Facilities", emoji: "📍" },
  { key: "premium_advanced", label: "Premium & Advanced Features", emoji: "💎" },
  { key: "smart_features", label: "Smart Property Features", emoji: "🤖" },
  { key: "energy_sustainability", label: "Energy & Sustainability", emoji: "🔋" },
  { key: "advanced_security", label: "Advanced Security", emoji: "🛡️" },
  { key: "building_infrastructure", label: "Building & Infrastructure", emoji: "🏢" },
  { key: "premium_lifestyle", label: "Premium Lifestyle", emoji: "🧘" },
  { key: "hotel_services", label: "Hotel-Like Services", emoji: "🛎️" },
  { key: "advanced_parking", label: "Advanced Parking", emoji: "🚗" },
  { key: "view_location_intel", label: "View & Location Intelligence", emoji: "🌆" },
  { key: "other", label: "Other", emoji: "✨" },
];
export const AMENITY_CATEGORY_OPTIONS = AMENITY_CATEGORIES.map((c) => c.key);
export function getAmenityCategory(key) {
  return AMENITY_CATEGORIES.find((c) => c.key === key) || AMENITY_CATEGORIES[AMENITY_CATEGORIES.length - 1];
}

export const AMENITY_ICONS = {
  roof_terrace: { label: "Roof terrace", Icon: Sun },
  parking: { label: "Parking", Icon: Car },
  swimming_pool: { label: "Swimming pool", Icon: Waves },
  pet_friendly: { label: "Pet friendly", Icon: PawPrint },
  home_office: { label: "Home office", Icon: Briefcase },
  concierge: { label: "Concierge", Icon: ConciergeBell },
  garden: { label: "Garden", Icon: Trees },
  gym: { label: "Gym", Icon: Dumbbell },
  wifi: { label: "Wifi", Icon: Wifi },
  air_conditioning: { label: "Air conditioning", Icon: Snowflake },
  heating: { label: "Heating", Icon: Flame },
  security: { label: "24/7 security", Icon: ShieldCheck },
  storage: { label: "Storage", Icon: Warehouse },
  ev_charging: { label: "EV charging", Icon: Zap },
  clubhouse: { label: "Clubhouse", Icon: Users },
  smart_tv: { label: "Smart TV", Icon: Tv },
  laundry: { label: "Laundry", Icon: WashingMachine },
  ventilation: { label: "Ventilation", Icon: Wind },
  gated_access: { label: "Gated access", Icon: Lock },
  cctv: { label: "CCTV", Icon: Camera },
  furnished: { label: "Furnished", Icon: Sofa },
  dining_area: { label: "Dining area", Icon: UtensilsCrossed },
  elevator: { label: "Elevator", Icon: Building2 },
  near_landmark: { label: "Near landmark", Icon: Landmark },
  sports_facility: { label: "Sports facility", Icon: Trophy },
  kids_area: { label: "Kids area", Icon: Baby },
  other: { label: "Other", Icon: Sparkles },

  // ---- Parking & Convenience ----
  covered_parking: { label: "Covered parking", Icon: Car },
  open_parking: { label: "Open parking", Icon: Car },
  power_backup: { label: "Power backup", Icon: BatteryCharging },
  water_supply: { label: "Water supply", Icon: Droplets },
  gas_pipeline: { label: "Gas pipeline", Icon: Flame },
  emergency_lift: { label: "Emergency lift", Icon: Building2 },
  wheelchair_access: { label: "Wheelchair accessibility", Icon: Accessibility },
  security_guard: { label: "Security guard", Icon: UserCheck },
  intercom: { label: "Intercom facility", Icon: PhoneCall },

  // ---- Outdoor & Lifestyle ----
  private_garden: { label: "Private garden", Icon: Flower2 },
  terrace: { label: "Terrace", Icon: PanelTop },
  private_terrace: { label: "Private terrace", Icon: PanelTop },
  jogging_track: { label: "Jogging track", Icon: Footprints },
  community_hall: { label: "Community hall", Icon: Users },
  lounge_area: { label: "Party/lounge area", Icon: PartyPopper },

  // ---- Security & Smart Features ----
  video_door_phone: { label: "Video door phone", Icon: Video },
  smart_lock: { label: "Smart door lock", Icon: KeyRound },
  smart_automation: { label: "Smart home automation", Icon: Cpu },
  fire_safety: { label: "Fire safety system", Icon: FlameKindling },
  smoke_detector: { label: "Smoke detector", Icon: AlertTriangle },
  fire_extinguisher: { label: "Fire extinguisher", Icon: FireExtinguisher },
  earthquake_resistant: { label: "Earthquake resistant structure", Icon: Shield },
  access_control: { label: "Access control", Icon: Fingerprint },
  visitor_management: { label: "Visitor management system", Icon: ClipboardList },

  // ---- Utilities & Infrastructure ----
  solar_water_heater: { label: "Solar water heater", Icon: Sun },
  solar_power: { label: "Solar power", Icon: SunMedium },
  rainwater_harvesting: { label: "Rainwater harvesting", Icon: CloudRain },
  sewage_treatment: { label: "Sewage treatment plant", Icon: Recycle },
  waste_disposal: { label: "Waste disposal", Icon: Trash2 },
  water_storage: { label: "Water storage", Icon: Droplet },
  borewell: { label: "Borewell", Icon: Droplet },

  // ---- Interior Features ----
  modular_kitchen: { label: "Modular kitchen", Icon: ChefHat },
  chimney: { label: "Chimney", Icon: Fan },
  wardrobes: { label: "Wardrobes", Icon: Shirt },
  walk_in_closet: { label: "Walk-in closet", Icon: DoorClosed },
  false_ceiling: { label: "False ceiling", Icon: Layers },
  premium_flooring: { label: "Premium flooring", Icon: Gem },
  wooden_flooring: { label: "Wooden flooring", Icon: TreePine },
  attached_bathroom: { label: "Attached bathrooms", Icon: Bath },
  study_room: { label: "Study room", Icon: BookOpen },
  pooja_room: { label: "Pooja room", Icon: Flame },
  servant_room: { label: "Servant room", Icon: Users },
  utility_room: { label: "Utility room", Icon: Wrench },

  // ---- Location & Nearby Facilities ----
  main_road_facing: { label: "Main road facing", Icon: Route },
  corner_property: { label: "Corner property", Icon: CornerDownRight },
  park_facing: { label: "Park facing", Icon: Trees },
  pool_facing: { label: "Pool facing", Icon: Waves },
  road_view: { label: "Road view", Icon: Route },
  city_view: { label: "City view", Icon: Building },
  school_nearby: { label: "School nearby", Icon: GraduationCap },
  hospital_nearby: { label: "Hospital nearby", Icon: HeartPulse },
  mall_nearby: { label: "Shopping mall nearby", Icon: ShoppingBag },
  metro_nearby: { label: "Metro/transit nearby", Icon: TrainFront },
  airport_connectivity: { label: "Airport connectivity", Icon: Plane },
  highway_connectivity: { label: "Highway connectivity", Icon: Route },
  restaurant_nearby: { label: "Restaurant/cafe nearby", Icon: UtensilsCrossed },
  market_nearby: { label: "Market nearby", Icon: ShoppingCart },

  // ---- Premium & Advanced Features ----
  sea_view: { label: "Sea/lake view", Icon: Waves },
  mountain_view: { label: "Mountain view", Icon: Mountain },
  panoramic_view: { label: "Panoramic view", Icon: Eye },
  private_pool: { label: "Private swimming pool", Icon: Waves },
  private_elevator: { label: "Private elevator", Icon: Building2 },
  home_theater: { label: "Home theater", Icon: Clapperboard },
  private_gym: { label: "Private gym", Icon: Dumbbell },
  rooftop_access: { label: "Rooftop access", Icon: Sun },
  sky_lounge: { label: "Sky lounge", Icon: Martini },
  housekeeping: { label: "Housekeeping service", Icon: SprayCan },
  property_management: { label: "Property management service", Icon: ClipboardCheck },

  // ---- Smart Property Features ----
  smart_lighting: { label: "Smart lighting", Icon: Lightbulb },
  smart_ac: { label: "Smart AC control", Icon: Thermometer },
  smart_curtains: { label: "Smart curtains", Icon: Blinds },
  smart_doorbell: { label: "Smart doorbell", Icon: Bell },
  smart_security_system: { label: "Smart security system", Icon: ShieldCheck },
  voice_assistant: { label: "Voice assistant integration", Icon: Radar },
  motion_sensor: { label: "Motion sensors", Icon: Radar },
  temperature_sensor: { label: "Temperature sensors", Icon: Thermometer },
  water_leak_detection: { label: "Water leak detection", Icon: Droplet },
  gas_leak_detection: { label: "Gas leak detection", Icon: Flame },
  energy_monitoring: { label: "Energy monitoring", Icon: Gauge },
  remote_monitoring: { label: "Remote home monitoring", Icon: Smartphone },
  mobile_app_control: { label: "Mobile app controlled devices", Icon: Smartphone },

  // ---- Energy & Sustainability ----
  solar_panels: { label: "Solar panels", Icon: SunMedium },
  renewable_energy: { label: "Renewable energy", Icon: Leaf },
  energy_efficient_appliances: { label: "Energy efficient appliances", Icon: BatteryCharging },
  energy_efficient_lighting: { label: "Energy efficient lighting", Icon: Lightbulb },
  green_building: { label: "Green building", Icon: Leaf },
  igbc_certified: { label: "IGBC certified", Icon: Award },
  leed_certified: { label: "LEED certified", Icon: Award },
  energy_rating: { label: "Energy rating", Icon: Gauge },
  greywater_recycling: { label: "Greywater recycling", Icon: Droplets },
  organic_waste_treatment: { label: "Organic waste treatment", Icon: Leaf },
  waste_segregation: { label: "Waste segregation", Icon: Trash2 },
  bicycle_parking: { label: "Bicycle parking", Icon: Bike },
  green_landscaping: { label: "Green landscaping", Icon: Trees },
  low_flow_plumbing: { label: "Low-flow plumbing", Icon: Droplet },
  natural_ventilation: { label: "Natural ventilation", Icon: Wind },

  // ---- Advanced Security ----
  multi_level_security: { label: "Multi-level security", Icon: ShieldCheck },
  gated_entry: { label: "Gated entry", Icon: Lock },
  rfid_vehicle_access: { label: "RFID vehicle access", Icon: Radar },
  anpr_recognition: { label: "ANPR vehicle recognition", Icon: Radar },
  facial_recognition: { label: "Facial recognition", Icon: ScanFace },
  biometric_access: { label: "Biometric access", Icon: Fingerprint },
  smart_access_cards: { label: "Smart access cards", Icon: KeyRound },
  cctv_monitoring: { label: "CCTV monitoring", Icon: Camera },
  lift_access_control: { label: "Lift access control", Icon: Building2 },
  panic_button: { label: "Emergency panic button", Icon: Siren },
  fire_alarm: { label: "Fire alarm", Icon: Siren },
  smoke_detection: { label: "Smoke detection", Icon: AlertTriangle },
  sprinkler_system: { label: "Sprinkler system", Icon: Droplets },
  fire_hydrant: { label: "Fire hydrant", Icon: FireExtinguisher },
  emergency_exit: { label: "Emergency exit", Icon: DoorClosed },
  security_control_room: { label: "Security control room", Icon: Radar },
  security_patrol: { label: "Security patrol", Icon: UserCheck },

  // ---- Building & Infrastructure ----
  earthquake_zone_rating: { label: "Earthquake zone rating", Icon: Shield },
  completion_certificate: { label: "Building completion certificate", Icon: Award },
  occupancy_certificate: { label: "Occupancy certificate", Icon: ClipboardCheck },
  fire_noc: { label: "Fire NOC", Icon: ClipboardCheck },
  structural_audit: { label: "Structural audit", Icon: Hammer },
  waterproofing: { label: "Waterproofing", Icon: Droplet },
  anti_termite_treatment: { label: "Anti-termite treatment", Icon: Shield },
  high_speed_elevators: { label: "High-speed elevators", Icon: Building2 },
  service_elevator: { label: "Service elevator", Icon: Building2 },
  separate_entrance: { label: "Separate entrance", Icon: DoorOpen },
  double_glazed_windows: { label: "Double-glazed windows", Icon: PanelTop },
  soundproof_windows: { label: "Soundproof windows", Icon: VolumeX },
  acoustic_walls: { label: "Acoustic walls", Icon: VolumeX },
  heat_reflective_glass: { label: "Heat-reflective glass", Icon: PanelTop },
  premium_facade: { label: "Premium facade", Icon: Building },
  basement_parking: { label: "Basement parking", Icon: Warehouse },
  mechanical_parking: { label: "Mechanical parking", Icon: Car },
  loading_area: { label: "Loading/unloading area", Icon: Truck },

  // ---- Premium Lifestyle ----
  infinity_pool: { label: "Infinity pool", Icon: Waves },
  rooftop_pool: { label: "Rooftop pool", Icon: Waves },
  heated_pool: { label: "Heated pool", Icon: Waves },
  jacuzzi: { label: "Jacuzzi", Icon: GlassWater },
  sauna: { label: "Sauna", Icon: Flame },
  steam_room: { label: "Steam room", Icon: Wind },
  spa: { label: "Spa", Icon: HandHeart },
  yoga_studio: { label: "Yoga studio", Icon: Leaf },
  meditation_room: { label: "Meditation room", Icon: Leaf },
  indoor_sports: { label: "Indoor sports", Icon: Dumbbell },
  outdoor_sports: { label: "Outdoor sports", Icon: Trophy },
  tennis_court: { label: "Tennis court", Icon: Trophy },
  basketball_court: { label: "Basketball court", Icon: Trophy },
  badminton_court: { label: "Badminton court", Icon: Trophy },
  cricket_practice_area: { label: "Cricket practice area", Icon: Trophy },
  cycling_track: { label: "Cycling track", Icon: Bike },
  pet_park: { label: "Pet park", Icon: Dog },
  kids_activity_center: { label: "Kids activity center", Icon: Baby },
  senior_lounge: { label: "Senior citizen lounge", Icon: Users },
  library: { label: "Library", Icon: BookOpen },
  coworking_space: { label: "Co-working space", Icon: Briefcase },
  business_center: { label: "Business center", Icon: Briefcase },
  gaming_zone: { label: "Gaming zone", Icon: Gamepad2 },
  movie_theater: { label: "Movie theater", Icon: Clapperboard },
  music_room: { label: "Music room", Icon: Music },
  party_hall: { label: "Party hall", Icon: PartyPopper },
  rooftop_lounge: { label: "Rooftop lounge", Icon: Martini },

  // ---- Hotel-Like Services ----
  laundry_service: { label: "Laundry service", Icon: WashingMachine },
  dry_cleaning: { label: "Dry cleaning", Icon: Shirt },
  room_service: { label: "Room service", Icon: HandPlatter },
  grocery_delivery: { label: "Grocery delivery", Icon: ShoppingBag },
  cab_booking: { label: "Cab booking", Icon: Car },
  car_wash: { label: "Car wash", Icon: Car },
  car_maintenance: { label: "Car maintenance", Icon: Wrench },
  pet_care: { label: "Pet care", Icon: Dog },
  babysitting: { label: "Babysitting", Icon: Baby },
  on_demand_maintenance: { label: "On-demand maintenance", Icon: Wrench },
  plumber_on_call: { label: "Plumber on call", Icon: Wrench },
  electrician_on_call: { label: "Electrician on call", Icon: Zap },
  technician_on_call: { label: "Technician on call", Icon: Wrench },
  security_assistance: { label: "Security assistance", Icon: Shield },
  guest_management: { label: "Guest management", Icon: Users },
  package_delivery_management: { label: "Package delivery management", Icon: Package },

  // ---- Advanced Parking ----
  dedicated_parking: { label: "Dedicated parking", Icon: Car },
  multiple_parking_slots: { label: "Multiple parking slots", Icon: Car },
  automated_parking: { label: "Automated parking", Icon: Car },
  fast_ev_charging: { label: "Fast EV charging", Icon: Zap },
  car_wash_facility: { label: "Car wash facility", Icon: Car },
  valet_parking: { label: "Valet parking", Icon: Car },
  car_service_area: { label: "Car service area", Icon: Wrench },
  two_wheeler_parking: { label: "Two-wheeler parking", Icon: Bike },
  parking_camera: { label: "Parking camera", Icon: Camera },

  // ---- View & Location Intelligence ----
  skyline_view: { label: "Skyline view", Icon: Building2 },
  garden_view: { label: "Garden view", Icon: Trees },
  park_view: { label: "Park view", Icon: Trees },
  pool_view: { label: "Pool view", Icon: Waves },
  lake_view: { label: "Lake view", Icon: Waves },
  river_view: { label: "River view", Icon: Waves },
  golf_course_view: { label: "Golf course view", Icon: Trees },
  main_road_view: { label: "Main road view", Icon: Route },
  sunrise_view: { label: "Sunrise view", Icon: Sunrise },
  sunset_view: { label: "Sunset view", Icon: Sunset },
  corner_unit: { label: "Corner unit", Icon: CornerDownRight },
  zero_traffic_view: { label: "Zero traffic view", Icon: Route },
  quiet_neighborhood: { label: "Quiet neighborhood", Icon: VolumeX },
  green_zone_view: { label: "Green zone view", Icon: Leaf },
};

export const AMENITY_ICON_OPTIONS = Object.keys(AMENITY_ICONS);

export function getAmenityIcon(key) {
  return AMENITY_ICONS[key]?.Icon || Sparkles;
}
